export const carouselImages = [
  "IMG_6562_bbg_crpoed.jpg",
  "000023.jpg",
  "PXL_20210621_062035140.jpg",
  "IMG_6162a.jpg",
  "Screen-Shot-2020-04-16-at-5.32.35-PM.png",
  "IMG_6207.JPG",
  "drawinga.jpg",
  "IMG_6510.jpg",
  "kites00578.png",
  "IMG_6562_bbg_crpoed.jpg",
  "kites01719.png",
  "IMG_6771.JPG",
  "matrix.png",
  "IMG_7036.JPG",
  "musicscape-81.png",
  "PXL_20210415_172701758.jpg",
];

export const imagesLinks = [
  [
    "書寫身體 風動筆畫",
    "/Writing-Body-Moving-Strokes",
    "82B6A502-4FB6-4811-915D-A4CDAC7587AEa.JPG",
  ],
  ["Seeding Her Feet", "/Seeding-Her-Feet", "PXL_20210910_173418394.jpg"],
  ["Rings 環", "/Rings", "Zi-Xian_Szu-Yi-Wang_GNKK.jpg"],
  [
    "You House 遊居之間",
    "/You-House",
    "Screen-Shot-2022-01-04-at-4.48.43-PM.png",
  ],
  [
    "Zi Yuan, A Spring Stroll 字園遊步",
    "/Zi-Yuan-A-Spring-Stroll",
    "PXL_20210415_161841914.jpg",
  ],
  ["Zi Xian at TENT", "/Zi-Xian-at-TENT", "Zi-Xian_Szu-Yi-Wang_GNKK.jpg"],
  [
    "Foreshore 漫步潮閒",
    "/Foreshore",
    "Screen-Shot-2020-04-16-at-5.32.35-PM.png",
  ],
  ["Shan yu Shu", "/Shan-yu-Shu", "IMG_6752a.jpg"],
  ["Ritual upon the Paper", "/Ritual-upon-the-Paper", "IMG_7032.JPG"],
  [
    "In-between the Post Urban",
    "/Writing-In-between-the-Post-Urban",
    "58604194_10156027972171128_4487323097183027200_o.jpg",
  ],
  [
    "Extension Park Vijversburg",
    "/Extension-Park-Vijversburg",
    "IMG_4594xx.jpg",
  ],
  ["Zi Xian 字閒", "/Zi-Xian-The-Hanzi-Space", "IMG_9328_bbg.jpg"],
  [
    "The Stage After",
    "/The-Stage-After",
    "Screen-Shot-2018-07-31-at-9.50.47-PM.png",
  ],
  [
    "Moving Drawings",
    "/Moving-Drawings",
    "Screen-Shot-2019-01-24-at-1.49.13-AM.png",
  ],
  ["Narrative Theatre", "/Narrative-Theatre", "a2-full-10.jpg"],
  ["Water, Air, Ambience", "/Water-Air-Ambience", "IMG_1247.JPG"],
  ["Narrative Rooms", "/Narrative-Rooms", "veil04718.png"],
  ["Hanzi on the Table", "/Hanzi-on-the-Table", "IMG_1703.jpg"],
  ["The Shining Matter", "/The-Shining-Matter", "IMG_6054aa.jpg"],
  ["Meet the Mountains", "/Meet-the-Mountains", "_MG_7730blue_s.jpg"],
  ["(un)Folded Clusters", "/un-Folded-Clusters", "DSC07413.JPG"],
  ["Visual music", "/Visual-music", "musicscape-81.png"],
];

export const works = [
  ["書寫身體 風動筆畫", "/Writing-Body-Moving-Strokes"],
  ["Seeding Her Feet", "/Seeding-Her-Feet"],
  ["Rings 環", "/Rings"],
  ["You House 遊居之間", "/You-House"],
  ["Zi Yuan, A Spring Stroll 字園遊步", "/Zi-Yuan-A-Spring-Stroll"],
  ["Zi Xian at TENT", "/Zi-Xian-at-TENT"],
  ["Foreshore 漫步潮閒", "/Foreshore"],
  ["Huai House 徊屋", "/Huai-House-Strolling-House"],
  ["Shan yu Shu", "/Shan-yu-Shu"],
  ["Ritual upon the Paper", "/Ritual-upon-the-Paper"],
  ["In-between the Post Urban", "/Writing-In-between-the-Post-Urban"],
  ["Extension Park Vijversburg", "/Extension-Park-Vijversburg"],
  ["Zi Xian 字閒", "/Zi-Xian-The-Hanzi-Space"],
  ["The Stage After", "/The-Stage-After"],
  ["Moving Drawings", "/Moving-Drawings"],
  ["Narrative Theatre", "/Narrative-Theatre"],
  ["Water, Air, Ambience", "/Water-Air-Ambience"],
  ["Narrative Rooms", "/Narrative-Rooms"],
  ["Hanzi on the Table", "/Hanzi-on-the-Table"],
  ["The Shining Matter", "/The-Shining-Matter"],
  ["(un)Folded Clusters", "/un-Folded-Clusters"],
  ["Meet the Mountains", "/Meet-the-Mountains"],
];

export const otherSections = [
  ["Film", "/Film"],
  ["Photo galleries", "/Photo-gallerie"],
  ["Visual music", "/Visual-music"],
  ["News", "/News"],
  ["Information", "/Information"],
  ["cv", "/cv"],
];
