import ImageLinksComponent from "@/components/ImageLinks";
import CarouselGallery from "@/components/CarouselGallery";
import { stageImages, stageLayouts } from "../constances";

export default function RingsPage() {
  return (
    <div className="font-ebgaramond flex min-h-screen bg-background text-foreground md:pl-60">
      {/* Main Content */}

      <main className="flex-1 sm:px-12 md:px-4">
        <div className="py-6 sm:py-12 px-8  space-y-12 bg-slate-0">
          {" "}
          {/* Title Section */}
          <div
            className="bg-orange-0 grid
           grid-cols-1
           gap-4
           sm:grid-cols-1 sm:gap-3
           md:grid-cols-2 md:gap-4
           lg:grid-cols-2 lg:gap-6
           auto-rows-min"
          >
            <div className="bg-red-0 col-span-1 row-span-1">
              {/* Item 1 */}
              <div>
                <p className="text-sm leading-relaxed space-y-2">
                  The Stage After: performing particles 後 舞 臺
                  <br />
                  <br />
                </p>
              </div>
            </div>
            <div className="bg-yellow-0 col-span-1 row-span-1">
              {/* Item 2 */}
              <div>
                <p className="text-sm leading-relaxed space-y-2 text-muted-foreground">
                  <em>
                    A showing & producing space with the audience’s memories and
                    the audio-visual generative installation
                  </em>
                </p>
              </div>
            </div>
            {/* Item 3 */}
            <div>
              {/* Project Meta */}
              <section className="space-y-4 border-border py-6">
                <div className="grid grid-cols-1 sm:grid-cols-1 gap-1 sm:gap-1 text-sm">
                  <div>
                    <span className="text-muted-foreground">Year</span>
                    <span className="ml-2">|</span>
                    <span className="ml-2">2017</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Type</span>
                    <span className="ml-2">|</span>
                    <span className="ml-2">
                      stage design, exhibiting & performing installation{" "}
                    </span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Location</span>
                    <span className="ml-2">|</span>
                    <span className="ml-2">
                      {" "}
                      deSingel (art & culture centre), Antwerp{" "}
                    </span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Material</span>
                    <span className="ml-2">|</span>
                    <span className="ml-2">
                      paper, acrylic, particles in kinds, light & shadow, sound
                    </span>
                  </div>
                </div>
              </section>
              {/* Exhibition Info */}
              <section className="space-y-4 text-sm leading-relaxed">
                <p className="text-muted-foreground">
                  <strong>
                    <br /> <br />
                    This project practices the theme—showing and producing
                    space—in a poetic but sustainable approach. The minimum
                    design (between tangible and intangible) amplifys the pure
                    effects of light and shadow, which are generated by the
                    soundtracks from deSingel programs.
                    <br /> <br />A conceptual video presents how the design,
                    while realized with existing programs, creates an immersive
                    experience in both the corridor and the audience’s mind.
                  </strong>
                </p>
                <p className="text-muted-foreground"></p>
                <p className="text-foreground"></p>
              </section>
            </div>
            <div className="col-span-1 row-span-1 bg-blue-0 gap-4">
              {/* Item 4 */}
              <div>
                {" "}
                {/* Quote */}
                {/* Main Description */}
                <section className="space-y-4 text-sm leading-relaxed">
                  <p>
                    <br />
                    It presents particles of light & shadows as visualization of
                    soundtracks.
                    <br />
                    <br />
                    In the corridor after every show, it aims to echo memories
                    in every audience’s mind.
                    <strong className="font-ebgaramond"></strong>
                  </p>
                </section>
              </div>
            </div>
            <div className="col-span-1 row-span-1 bg-blue-0">
              {/* Item 5 */}
              <div>
                <section className=" text-foreground space-y-1">
                  <p>
                    This project practices the theme—showing and producing
                    space—in a poetic but sustainable approach. The minimum
                    design (between tangible and intangible) amplifys the pure
                    effects of light and shadow, which are generated by the
                    soundtracks from deSingel programs.
                    <br />
                    <br />A conceptual video presents how the design, while
                    realized with existing programs, creates an immersive
                    experience in both the corridor and the audience’s mind.
                  </p>
                </section>
                <section className="text-sm text-muted-foreground space-y-1">
                  <p></p>
                </section>
              </div>
            </div>

            <div className="col-span-1 row-span-1 bg-blue-0">
              {/* Item 6 */}
              <div>
                <section className=" text-foreground space-y-1">
                  <p>
                    The ‘canyon’ with its inclined floor leads to various
                    patterns of movement, degrees of light, perceptions of both
                    depth & darkness. As our fantasies in the theatre boxes are
                    extended to the passage—which here serves as The Stage
                    After. We walk, immerse in the imaginary world when scenes*
                    appear in our mind touched by those performing particles—
                    visualized music in light & shadow.
                    <br />
                    <br />
                    The soundtracks of the performance are realized/visualized
                    by the particles, movements, light & shadow. The design
                    applies a dynamic sound system that spreads the music & its
                    vibration triggering the performing particles.
                  </p>
                </section>
                <section className="text-sm text-muted-foreground space-y-1">
                  <p></p>
                </section>
              </div>
            </div>
          </div>
          <div
            className="
             grid
             grid-cols-1
             md:grid-cols-[1fr_3fr_1fr]
             w-full
             gap-5"
          >
            <span>
              <section className=" text-muted-foreground space-y-1">
                Combined with one upcoming performance at deSingel—the chosen
                site for this thematic project—the video shows how the design
                concept « The Stage after » aims to create an immersive
                experience and resonance in the audience’s mind while they leave
                through the corridor between the venues.
                <br />
                <br />
              </section>
            </span>
            <span>
              {" "}
              <div className="w-full aspect-video">
                <iframe
                  src="https://player.vimeo.com/video/255352163"
                  className="w-full h-full"
                  allow="autoplay; fullscreen; picture-in-picture"
                  allowFullScreen
                />
              </div>
            </span>
            <span>
              <section className=" text-muted-foreground space-y-1">
                The Stage After (2017) by Szu-Yi Wang
                <br />
                <br />
                _Used trailer clips |  « I Will Fall For You » by Sidi Larbi
                Cherkaoui & Woodkid. Directed by Sidi Larbi Cherkaoui & Yoann
                Lemoine (source) Choreography: Sidi Larbi Cherkaoui; music: «
                Land of All » by Woodkid; performer: Drew Jacoby & Matt Foley 
                <br />
                <br />* This video is made for demonstrating the design concept
                during the study. It’s not used for any commercial purpose. All
                rights of the trailer and the art work are reserved to the
                artists above.   The video will be removed upon request of the
                copyright holders. If you have any question, please contact me.
                Thank you.
              </section>
            </span>
          </div>
          {/* Title Section */}
          <CarouselGallery images={stageImages} layouts={stageLayouts} />
          <p className="text-center"></p>
          <p className="text-xs text-muted-foreground pt-12 border-t border-border"></p>
          {/* Footer */}
          <ImageLinksComponent />
          <footer className="text-xs text-muted-foreground pt-12 border-t border-border">
            <p>©SZU-YI WANG. 2026</p>
          </footer>
        </div>
      </main>
      <style>
        {`
        .wrapper {
          display: grid;
          grid-template-columns: 1fr 3fr 1fr;
          width: 100%;
        }

        .main-image {
          width: 100%;
          height: auto;
          display: block;
        }
        `}
      </style>
    </div>
  );
}
